### ISSUE TITLE
fix deploy github pages

### ISSUE THREAD

**Issue by xmimiex** [xmimiex/vue3-ssr-template#31]
Depuis mon refacto avec vuepress@next.

- le workflow github build bien la doc et la dépose correctement sur la branche gh-pages : https://github.com/xmimiex/vue3-ssr-template/actions/runs/1690231665 (contenu de la branche : https://github.com/xmimiex/vue3-ssr-template/tree/gh-pages)
- par contre le workflow qui écoute les push sur cette branche pour mettre à jour le site est en échec : https://github.com/xmimiex/vue3-ssr-template/actions/runs/1690233352 

Config Pages
![image](https://user-images.githubusercontent.com/6469845/149290444-7b2be50c-e5ff-463d-bbb3-b32f78e4878b.png)

**Comment by xmimiex** [comment]
résolu, il manquait le "base: /vue3-ssr-template" dans la config de vuepress ^^

**Comment by mrzdevcore** [comment]
cool
